### ISSUE TITLE
Adding params does anything

### ISSUE THREAD

**Issue by vladop** [Wufe/react-particles-js#10]
This is my code:

  <Particles
                        params={{
                            "number": {
                                "value": 800,
                                "density": {
                                    "enable": true,
                                    "value_area": 800
                                }
                            },
                            "particles": {
                                "color": {
                                    "value": "#AABBDD"
                                },
                                line_linked: {
                                    shadow: {
                                        enable: true,
                                        color: "#AABBCC",
                                        blur: 5
                                    }
                                }
                            }
                        }}>

It is always some. It seems whatever I do I get same result, so params is not working!

**Comment by Wufe** [comment]
I tried your configuration on index.html. It works. 
If you are not sure why it doesn't work, please give some code to reproduce the situation.

**Comment by Wufe** [comment]
Closing the issue for now. Feel free to post if you think there's a problem.
