### ISSUE TITLE
missing type

### ISSUE THREAD

**Issue by severance88** [Wufe/react-particles-js#102]
Hello Simone.

Thanks for the awesome job.

The typings file should be updated for `particles.color.value`. At the moment the typing only accepts a single string, but it should also accept an array of strings. I've changed it on my side with success.

Can you add it? Or would you accept a PR to fix this? I've never contributed or opened an issue to open source before.

Thank you.
Regards

**Comment by Wufe** [comment]
Thanks for the feedback. `v2.7.1` should fix the issue
