### ISSUE TITLE
plygon mask with SVG image does not work 

### ISSUE THREAD

**Issue by ravihani** [Wufe/react-particles-js#104]
Library works perfectly for simple, bubble, multiple images but does not work for Polygon 
mask. Please see below code. Am i missing something?  It just shows a blank screen. Could you help please.

```
import React, { Component } from "react";
import Particles from "react-particles-js";
import "./Home.css";

export class Home extends Component {
  render() {
    return (

        <div class="particles">
          <Particles
            params={{
              fps_limit: 28,
              particles: {
                number: { value: 200, density: { enable: false } },
                line_linked: { enable: true, distance: 30, opacity: 0.4 },
                move: { speed: 1 },
                opacity: {
                  anim: {
                    enable: true,
                    opacity_min: 0.05,
                    speed: 2,
                    sync: false
                  },
                  value: 0.4
                }
              },
              polygon: {
                enable: true,
                scale: 0.5,
                type: "inline",
                move: { radius: 10 },
                url: "/smalldeer.svg",
                inline: { arrangement: "equidistant" },
                draw: {
                  enable: true,
                  stroke: { color: "rgba(255, 255, 255, .2)" }
                }
              },
              retina_detect: false,
              interactivity: {
                events: { onhover: { enable: true, mode: "bubble" } },
                modes: { bubble: { size: 6, distance: 40 } }
              }
            }}
          />
        </div>
    );
  }
}

export default Home;
```

**Comment by cc-visionary** [comment]
Same with me, this is the error given to me whenever I write   
```
polygon: { 
    enable:true 
}
```
![image](https://user-images.githubusercontent.com/22016684/77871588-30957f80-7277-11ea-888e-f7eb4d447b96.png)

**Comment by matteobruni** [comment]
@ravihani the path you specified in the config exists?

```json
url: "/smalldeer.svg",
```

---

@cc-visionary the config you specified isn't complete

```json
polygon: { 
    enable:true 
}
```

you have to specify at least the url of the svg image

---

Remember that the svg image should be a single path one, all others will be ignored. If none you won't see anything.

**Comment by ravihani** [comment]
@matteobruni 
Yes, the path exists because the image is visible when i use multiple images configuration. Unlike @cc-visionary  i am not receiving any errors.

**Comment by matteobruni** [comment]
@ravihani Can you share the image? Is it the smalldeer.svg in the sample?

**Comment by ravihani** [comment]
Sorry, my bad. my Chrome console log level was set to display only information.  It's changed back to  verbose and it did show the actual error, which was causing the issue. 

cannot read property 'numberOfItems' of undefined when polygon is on
 
Adding this reference resolved the issue.
<script src="https://cdn.rawgit.com/progers/pathseg/master/pathseg.js"></script>

**Comment by debubaba** [comment]
I am still getting this issue. I have added the reference and my image is a single path one too. Only polygon mask isnt working. What could the issue be?

<Particles
          params={{
            fps_limit: 28,
            particles: {
              number: { value: 100, density: { enable: false } },
              line_linked: { enable: true, distance: 30, opacity: 0.4 },
              move: { speed: 1 },
              opacity: {
                anim: {
                  enable: true,
                  opacity_min: 0.05,
                  speed: 2,
                  sync: false
                },
                value: 0.4
              }
            },
            polygon: {
              debug: true,
              enable: true,
              scale: 0.5,
              type: "inline",
              move: { radius: 10 },
              url: "/avatar3.svg",
              inline: { arrangement: "equidistant" },
              draw: {
                enable: true,
                stroke: { color: "rgba(255, 255, 255, .2)" }
              }
            },
            retina_detect: false,
            interactivity: {
              events: { onhover: { enable: true, mode: "bubble" } },
              modes: { bubble: { size: 6, distance: 40 } }
            }
          }} />

**Comment by Wufe** [comment]
Frequent reasons for the polygon mask to not show up are:
- missing pathseg polyfill script
- svg composed by more than one path (only first one is used right now)
- svg not available publicly (is the svg reachable through `<your host>/file.svg` ? )
- particles color are the same as the background, so nothing shows up

**Comment by V-Sharma10** [comment]
i am getting TypeError: this.svg is undefined

included pathseg in public html file,

and the params is as below :

params={{
                  "fps_limit": 28,
                  "particles": {
                      "number": {
                          "value": 200,
                          "density": {
                              "enable": false
                          }
                      },
                      "line_linked": {
                          "enable": true,
                          "distance": 30,
                          "opacity": 0.4
                      },
                      "move": {
                          "speed": 1
                      },
                      "opacity": {
                          "anim": {
                              "enable": true,
                              "opacity_min": 0.05,
                              "speed": 2,
                              "sync": false
                          },
                          "value": 0.4
                      }
                  },
                  "polygon": {
                      "enable": true,
                      "scale": 0.5,
                      "type": "inline",
                      "move": {
                          "radius": 10
                      },
                      "url": "./index.svg",
                      "inline": {
                          "arrangement": "equidistant"
                      },
                      "draw": {
                          "enable": true,
                          "stroke": {
                              "color": "rgba(255, 255, 255, .2)"
                          }
                      }
                  },
                  "retina_detect": false,
                  "interactivity": {
                      "events": {
                          "onhover": {
                              "enable": true,
                              "mode": "bubble"
                          }
                      },
                      "modes": {
                          "bubble": {
                              "size": 6,
                              "distance": 40
                          }
                      }
                  }
              }}

**Comment by matteobruni** [comment]
@V-Sharma10 you missed the sag file, anyway you can try using this working sample

https://codesandbox.io/s/react-particles-js-polygon-mask-sample-with-tsparticles-xb2fu?file=/src/App.js

**Comment by V-Sharma10** [comment]
thank you, that helped the problem was in the svg file itself  ;)

**Comment by Wufe** [comment]
Answers given, closing.

**Comment by Avivhdr** [comment]
> Frequent reasons for the polygon mask to not show up are:
> 
> * missing pathseg polyfill script
> * svg composed by more than one path (only first one is used right now)
> * svg not available publicly (is the svg reachable through `<your host>/file.svg` ? )
> * particles color are the same as the background, so nothing shows up

I have a Code sandbox in which I used the deer SVG, I added pathseg polyfill, URL is accessible publicly, and color doesn't match the background.

I would appreciate it if you can take a look, please.

https://codesandbox.io/s/polygon-mask-s7bsz?file=/src/index.js

**Comment by matteobruni** [comment]
I don't understand what is not working. White particles with a `pink` background is a configuration that hurt in my eyes.

You didn't set the color of the particles, so they are white by default. If I set a `black` background I see them well and animated too.

**Comment by ohmygaugh-crypto** [comment]
Hello Y'all. I've been facing the related issues addressed above. All super helpful, but I'm unable to get the particles to trace the path of my svg image as a polygon mask. (For simplicity I decided to use the create-react-app logo). Is this particular logo's "path" not yet compatible with tsparticles?

I'll provide a code sandbox instance soon, so everyone can see as reference.

**Comment by ohmygaugh-crypto** [comment]
I'd appreciate any feedback you may have:

https://codesandbox.io/s/silly-breeze-shjl0?file=/README.md

**Comment by matteobruni** [comment]
Hi @ohmygaugh-crypto, I've seen your SVG file but it has a `<circle>` tag that is not supported

**Comment by ohmygaugh-crypto** [comment]
Hey @matteobruni thanks for the tip. I've been able to render all the templates you've provided, so thank you for all those examples. Also, I just realized that my default GitHub image may inadvertently be giving you the eye troubles you referenced earlier.. lol my b

**Comment by ohmygaugh-crypto** [comment]
Hey @matteobruni one last question for you if you don't mind... Could you please elaborate on how you converted your local svg file(s) to become pubically accessible through: "url": "https://cdn.matteobruni.it/images/particles/smalldeer.svg"? I think (hopefully) this may be helpful for those who come across this thread.

**Comment by matteobruni** [comment]
> Hey @matteobruni one last question for you if you don't mind... Could you please elaborate on how you converted your local svg file(s) to become pubically accessible through: "url": "https://cdn.matteobruni.it/images/particles/smalldeer.svg"? I think (hopefully) this may be helpful for those who come across this thread.
> 
> 

It's a server side configuration, it enables different origins to make requests, I did it in ASP.NET core, try searching about CORS for your technology

**Comment by ohmygaugh-crypto** [comment]
The "#codevember - 5 - Particles Brain - Made with tsParticles" sample you did is the most similar to my use case.

[https://dev.to/matteobruni/codevember-5-particles-brain-made-with-tsparticles-ncd](url)
