### ISSUE TITLE
How to render components on top of the particles? 

### ISSUE THREAD

**Issue by FrozenFury** [Wufe/react-particles-js#108]
I can't wrap child components in it for some reason

**Comment by Wufe** [comment]
As a canvas cannot contain child DOM elements and to avoid messing up with css the component library itself does not allow for children elements to be rendered.

To place the component in background you should use style positioning.

Check the [demo repository](https://github.com/wufe/react-particles-js-demo) as it allows other components to be placed on top of the canvas.

**Comment by matteobruni** [comment]
@FrozenFury is this something similar of what you wanted to do?

https://codesandbox.io/s/react-login-on-particles-masking-background-ll9lh?file=/src/styles.css:0-130

**Comment by FrozenFury** [comment]
yes, thank you!
