### ISSUE TITLE
Particles doesn't appear in React

### ISSUE THREAD

**Issue by dulangaheshan** [Wufe/react-particles-js#110]
I installed react-particles-js as the instructions on the README.md file, but i can't see the particles in view it shows only white background in both chrome and edge browsers.so i checked browse console for find any errors. but there were no any error,

but when i right click on UI it shows 'save image as' and copy image options, when i select save or copy option there is particles on that image

**Comment by matteobruni** [comment]
Can you share the configuration used and the css relative to the particles container?
If not, can you try to add a section in the configuration like this:

```javascript
{
    /* your config */
    particles: { /* your config */ },
    /* your config */
    background: { color: "#000" } // just add this
}
```

The canvas should become black and if there are white particles you should see them.

**Comment by dulangaheshan** [comment]
> Can you share the configuration used and the css relative to the particles container?
> If not, can you try to add a section in the configuration like this:
> 
> ```js
> {
>     /* your config */
>     particles: { /* your config */ },
>     /* your config */
>     background: { color: "#000" } // just add this
> }
> ```
> 
> The canvas should become black and if there are white particles you should see them.

thanks it works

**Comment by dulangaheshan** [comment]
Issue was i didn't apply background color
