### ISSUE TITLE
centering svg polygon

### ISSUE THREAD

**Issue by xeroe** [Wufe/react-particles-js#114]
hello,
is it possible to influence the position of the svg polygon when using this option?
the polygon always appears on the bottom right edge of the canvas for me, but id like to center it to use it under an image.

**Comment by matteobruni** [comment]
Hi @xeroe can you share the image? Probably it has a bigger size and the main path has coordinates to center it, the polygon is already centered in the canvas.
Anyway the position it's a feature that can be implemented.

**Comment by matteobruni** [comment]
@xeroe if you install react-particles-js 3.1.0 version you can install tsParticles 1.13.0 with position options for `polygon`.

You can read more [here](https://github.com/matteobruni/tsparticles/wiki/tsParticles-Options#polygon-mask)
