### ISSUE TITLE
Extremely simple particle is not working. 

### ISSUE THREAD

**Issue by GaganBhat** [Wufe/react-particles-js#115]
This is likely an issue with the way I am doing something, but I have a dead-simple react project in a code box and I can't seem to get it to show the particles regardless of what I do. I copied the exact same particle configuration from the [demo](https://rpj.bembi.org/) page.

The code sandbox is https://codesandbox.io/s/minimal-zhvyg?file=/src/index.js

**Comment by matteobruni** [comment]
The particles default color is white, try changing it or change the background.

Here you can find all the options: https://github.com/matteobruni/tsparticles/blob/master/README.md#options

**Comment by GaganBhat** [comment]
Thank you, @matteobruni, I can't believe I missed that. That was it.

**Comment by GaganBhat** [comment]
![image](https://user-images.githubusercontent.com/25236969/79095845-249ec880-7d21-11ea-99d3-0739ed09ac04.png)
Beautiful, absolutely beautiful. Thank you for creating this!
