### ISSUE TITLE
SVG not rendering in Safari

### ISSUE THREAD

**Issue by mr-skyaakash** [Wufe/react-particles-js#119]
When an svg is listed as a source in the images array, it is not being loaded into the canvas in Safari. Works on Chrome and Firefox perfectly. Tested on versions 2.7.0 and 3.1.0. PNG and JPG works alright.  Also the same SVG when referenced from an img tag, renders perfectly. I assumed it would be because of the way svg was being served by webpack. Later, even after setting it's content-type to image/svg+xml, i still get the issue. Please help!

**Comment by matteobruni** [comment]
Hi @mr-skyaakash, can you share the image and the config to replicate the issue?

**Comment by mr-skyaakash** [comment]
Sharing the config, but am not allowed to share the screenshot due to certain policies!

`<Particles
        params={{
          particles: {
            number: {
              value: 30,
              density: {
                enable: true,
                value_area: 800,
              },
            },
            line_linked: {
              enable: false,
            },
            move: {
              speed: 1,
              out_mode: 'out',
            },
            shape: {
              type: ['images', 'circle'],
              images: [
                {
                  src: '/public/assets/landing-page/someIcon1.svg',
                  height: 10,
                  width: 10,
                },
                {
                  src: '/public/assets/landing-page/someIcon2.svg',
                  height: 10,
                  width: 10,
                },
              ],
            },
            size: {
              value: 15,
              random: false,
            },
          },
          retina_detect: false,
          interactivity: {
            events: {
              onhover: {
                enable: true,
                mode: 'bubble',
              },
            },
            modes: {
              bubble: {
                size: 20,
                distance: 40,
              },
            },
          },
        }}
      />`

**Comment by matteobruni** [comment]
@mr-skyaakash I didn't mean the screenshot, just the SVG images you are using, if it's possible.

I have samples with SVG that works in Safari, that's why I'm asking

**Comment by mr-skyaakash** [comment]
Any of the fontawesome svgs, or for better reference, the svg from this demo page : https://rpj.bembi.org/k8s.2d579d24.svg.

P.S : CORS has been taken care, so it loads just fine.

**Comment by matteobruni** [comment]
Ok those file are working to me. Safari version?

**Comment by mr-skyaakash** [comment]
Safari 13.0.5

**Comment by matteobruni** [comment]
I've created a pen on codepen with the image drawing method taken by v3.1.0.

<https://codepen.io/matteobruni/pen/BaoRGZd>

Does this pen work in your safari?

**Comment by mr-skyaakash** [comment]
Yes, this works fine! Can we have a codesandbox using just a Particle component with an svg image which works fine for you?

**Comment by matteobruni** [comment]
Checkout this, it's a tsParticles CodePen but it's the react-particles-js 3.x core.

<https://codepen.io/matteobruni/pen/XWmRooM>

Anyway I think I forgot a thing about 3.1.0 version, that seems to be the real issue.

Checkout this closed issue

<https://github.com/Wufe/react-particles-js/issues/118#issuecomment-619385072>

The issue is that 3.1.0 version still uses tsParticles 1.12.11 that has a bug about `'images'` shape type.

You can try upgrade tsParticles to 1.13.3 installing after react-particles-js 3.1.0 or switch to `'image'` shape type.



```<Particles params={{
    particles: {
        number: {
            value: 30,
            density: {
                enable: true,
                value_area: 800
            }
        },
        line_linked: {
            enable: false
        },
        move: {
            speed: 1,
            out_mode: 'out'
        },
        shape: {
            type: ['image', 'circle'], // here image instead of images
            images: [ // here you can use image or images, it's the same
                {
                    src: '/public/assets/landing-page/someIcon1.svg',
                    height: 10,
                    width: 10,
                },
                {
                    src: '/public/assets/landing-page/someIcon2.svg',
                    height: 10,
                    width: 10
                }
            ]
        },
        size: {
            value: 15,
            random: false
        }
    },
    retina_detect: false,
    interactivity: {
        events: {
            onhover: {
                enable: true,
                mode: 'bubble'
            }
        },
        modes: {
            bubble: {
                size: 20,
                distance: 40,
            },
        },
    },
}} />```

**Comment by matteobruni** [comment]
Anyway if you need some FontAwesome icons you can checkout this sample too:

<https://codepen.io/matteobruni/pen/QWbrLoK>

Text particles can be configured in version 3.x

**Comment by mr-skyaakash** [comment]
Ah! it works now with the new config. Closing this issue! Request you to update all the docs! :) Ciao

**Comment by matteobruni** [comment]
@mr-skyaakash the 3.2.0 version with the shape type fix is available, if you want to keep the old config.
