### ISSUE TITLE
The demo website not working

### ISSUE THREAD

**Issue by superoo7** [Wufe/react-particles-js#12]
The demo website is down: [https://particles-demo-dedqzqdvns.now.sh/](https://particles-demo-dedqzqdvns.now.sh/)
![img](https://image.ibb.co/kwwMw5/Screen_Shot_2017_09_26_at_10_47_05_AM.png)

**Comment by Wufe** [comment]
thanks. the link has expired, I'll provide another one asap.

**Comment by Wufe** [comment]
Link updated!
