### ISSUE TITLE
How to set this as the background of another element, instead of the whole screen?

### ISSUE THREAD

**Issue by silverben10** [Wufe/react-particles-js#125]
I'm trying to add this particle animation as the background of a `<header>` section on my site, but I can't work out the proper way to get it to display as the header's background - filling to 100% the height of the header - and then stopping.

**Comment by matteobruni** [comment]
Hi @silverben10 

Does this sample helps?

https://codesandbox.io/s/laughing-pine-hdi1z?file=/src/App.js

**Comment by MightyPhoenix** [comment]
@matteobruni Thanks! This kind of worked for me. Took around 30mins to figure out the CSS.

**Comment by silverben10** [comment]
That worked perfectly, thanks @matteobruni!
