### ISSUE TITLE
Color property doesn't get applied on image shape which is svg.

### ISSUE THREAD

**Issue by Arshazar** [Wufe/react-particles-js#129]
I used it before and it worked smoothly, but when I use recent update which uses tsparticles, when I use "image" property, color won't be changed!
I use latest versions of  react and afterjs... svg images load, but their color does not!

```
color: {
            value: '#fff',
        },
```

**Comment by matteobruni** [comment]
Hello @Arshazar,

Thanks for the report, I never thought about parsing SVG color, so SVG images are used like all the others. I'll work on this issue ASAP.

**Comment by Arshazar** [comment]
Thanks @matteobruni  , I guess it was because of the update... as it did work in previous version...

**Comment by matteobruni** [comment]
Yes it’s my fault, I’m already working on that.

Do you have a SVG to share for making tests? Otherwise I’ll search one later.

**Comment by Arshazar** [comment]
@matteobruni Sure, you can try this out: 
[](https://www.clipartmax.com/middle/m2H7i8Z5m2K9K9A0_file-simpleicons-interface-gear-wheel-in-black-svg-material-design-setting-icon/
)

**Comment by Arshazar** [comment]
@matteobruni Sure, you can try this out: 
[https://www.clipartmax.com/middle/m2H7i8Z5m2K9K9A0_file-simpleicons-interface-gear-wheel-in-black-svg-material-design-setting-icon/](url)

**Comment by matteobruni** [comment]
Hi @Arshazar, if you install tsParticles 1.14.3 manually you should have the fix.

Some notes about it:
1. The replace script, like the old version, replaces colors. It doesn't add them, if a SVG image has no color it will be displayed always black
2. The SVG file should be simple, namespaces can break browser compatibility, I've tested this version with one of your SVG (adding colors in code) in Safari, Chrome and Firefox.
3. The color replace option is disabled by default so if you need it you can enable it where you specify the `src` property. The replace option is `replaceColor`.

Hope everything works as expected

**Comment by Arshazar** [comment]
Hey @matteobruni , Thank you for the description :)
