### ISSUE TITLE
Canvas is always empty

### ISSUE THREAD

**Issue by oklex** [Wufe/react-particles-js#130]
(help wanted)
I've tried copying the configurations in 'https://rpj.bembi.org/' but the rendered canvas is empty. I tried on version 2.4 and after installing tsParticles but the canvas (with any of the provided configurations) is always empty. 

I reproduced this after deleting and re-installing node_modules, and running on another computer. This is my repo which is having troubles for reference: https://github.com/oklex/richmun-site

**Comment by matteobruni** [comment]
Have you tried changing the color of the particles?
I'm not sure about it, but it seems particles have no color (white default) and background seems white too.

**Comment by oklex** [comment]
That does it ":D this has been an embarrassing request - thank you for your quick assistance!

**Comment by matteobruni** [comment]
Happens sometimes, don’t worry
