### ISSUE TITLE
Uncaught TypeError: Cannot read property 'loadCanvas' of undefined

### ISSUE THREAD

**Issue by lstrive-yn** [Wufe/react-particles-js#132]
when the router changeing in nextjs project, this error occured

The configation of {ssr: false} has been used

what can i do， thanks

**Comment by matteobruni** [comment]
Which version are you using? Can you share some code?

**Comment by lstrive-yn** [comment]
> Which version are you using? Can you share some code?
I just use dynamic to dynamic import the custom Particles Component like so 
`const Particles = dynamic(() => import('react-particles-js'), { ssr: false });`
the version of nextjs is the latest(9.0.0) and the version of react-particles-js is v3.2.1

thanks again

**Comment by matteobruni** [comment]
I tried replicate the issue hehe: https://codesandbox.io/s/pensive-cache-n7891?file=/pages/index.js

But I got no errors, everything work fine as expected

**Comment by lstrive-yn** [comment]
> I tried replicate the issue hehe: https://codesandbox.io/s/pensive-cache-n7891?file=/pages/index.js
> 
> But I got no errors, everything work fine as expected

I really don't know what happened, I did nothing but it works fine now😢 haha~

Thank you for your patience~
