### ISSUE TITLE
Change Params with respect to screen width

### ISSUE THREAD

**Issue by zhuleyan** [Wufe/react-particles-js#135]
I am trying to design a responsive website. And when the screen is of a mobile phone's size, I want the number of particles to be fewer. If it has the same number as that in a pc version, the particles will look very crowded.
So is it possible that the params can be changed when the screen size changes? Thank you!

**Comment by matteobruni** [comment]
Have you tried https://github.com/matteobruni/tsparticles first? That issue should be fixed using the `density` property inside `particles.number`.

You can try it here: https://codepen.io/matteobruni/pen/mdVrbOv

**Comment by matteobruni** [comment]
Hi @zhuleyan,

This code sandbox uses `density` property: https://codesandbox.io/s/amazing-thompson-ryhbx?file=/src/App.js

If you resize the window and refresh the page you see less particles.
