### ISSUE TITLE
Can't Import my Image in the polygon configuration

### ISSUE THREAD

**Issue by shrey** [Wufe/react-particles-js#136]
Hey @Wufe , love the library, I saw the deer example, and tried to convert my image into a .svg file for my personal website, but it didn't work, any advice or tips upon how to make a working svg from jpeg, or any tools where I can draw up a vector image of myself and convert it to .svg?

**Comment by matteobruni** [comment]
Hi @shrey 

Inkscape (https://inkscape.org/release/inkscape-1.0/) is a good tool to create SVG if you want, I don't know if it converts other images too.

About the Polygon Mask feature your image should be composed with `<path>` tags, other tags would not be used, you can check the svg code to be sure
