### ISSUE TITLE
Canvas is rendering nothing...

### ISSUE THREAD

**Issue by faris** [Wufe/react-particles-js#138]
I tried using the nasa defaults on https://particles.matteobruni.it/# and changed the colours of the particles to be black, yet I am still unable too see anything.

I am using this for personal website on here (if you want to take a closer look) : 
https://github.com/faris/Personal-Website

Tested using Firefox/Chromium on Linux (Manjaro if it helps)

Any pointers on getting this working, would be greatly appreciated :)

Thanks,
Faris

**Comment by matteobruni** [comment]
Hi @faris,

I've checked your repository and the error is in the `jsx` file:

```jsx
<Particles params={{particlesConfig}} />
```

but this should be: 

```jsx
<Particles params={particlesConfig} />
```

You can see a working sample here: https://codesandbox.io/s/modest-williamson-onf70?file=/src/particles.json

**Comment by faris** [comment]
Ooops haha.

Thanks so much for the quick help and response @matteobruni
