### ISSUE TITLE
Failed to minify the code from this file: ./node_modules/tsparticles/dist/Options/Classes/OptionsColor.js:4

### ISSUE THREAD

**Issue by atarazavi** [Wufe/react-particles-js#139]
Hi,
I've used and implemented your great library, and everything work well!
When I try to **Build**  I face this error:
`Failed to minify the code from this file: ./node_modules/tsparticles/dist/Options/Classes/OptionsColor.js:4`
I have no idea what to do?!

`"react-particles-js": "^3.2.1",`

**Comment by matteobruni** [comment]
Hi @atarazavi, can you explain how to reproduce the issue?

**Comment by lindelof** [comment]
https://github.com/lindelof/particles-bg

**Comment by AftabFalak** [comment]
same error. any solution?

**Comment by matteobruni** [comment]
Hi @AftabFalak, can you explain how to reproduce the issue?
