### ISSUE TITLE
cannot initialize particles later after screen was rendered

### ISSUE THREAD

**Issue by mereka-ta** [Wufe/react-particles-js#143]
I need to render the particles at some time after app screen was rendered, I tried set in state.

This is working because I set it before app screen render

```
import ParticleComponent from './ParticleComponent';

const App = () => {
    const [renderParticle, setRenderParticle] = useState(null);

   if(renderParticle===null) {
       setRenderParticle(<ParticleComponent />)
  }

   return (
       <div class="main">
             {renderParticle}
       </div>
   );
}
```

Then, I tried set the component at a later time using setTimeout, the particles are not showing.

```
if(renderParticle===null) {
    setTimeout(()=>{
         setRenderParticle(<ParticleComponent />)
    }, 100)
}
```

Any other approach for my case?

**Comment by Wufe** [comment]
You can use a boolean to condition the rendering, like this https://codesandbox.io/s/143-latest-with-delayed-initialization-i9lsr?file=/src/index.js
