### ISSUE TITLE
heigth and width not responding 

### ISSUE THREAD

**Issue by afhaider** [Wufe/react-particles-js#145]
<Particles  className="site-layout-background" style={{width:'700',height:'900px',backgroundColor:'#00008'}}
    params={{
	    "particles": {
	        "number": {
	            "value": 160,
	            "density": {
	                "enable": false
	            }
	        },
	        "size": {
	            "value": 10,
	            "random": true
	        },
	        "move": {
	            "direction": "bottom",
	            "out_mode": "out"
	        },
	        "line_linked": {
	            "enable": false
	        }
	    },
	    "interactivity": {
	        "events": {
	            "onclick": {
	                "enable": true,
	                "mode": "remove"
	            }
	        },
	        "modes": {
	            "remove": {
	                "particles_nb": 10
	            }
	        }
	    }
	}} />

how can i reduce this height

**Comment by matteobruni** [comment]
I don't understand the issue, you set a `900px` height in `style` attribute. Am I missing something?

**Comment by afhaider** [comment]
i mean i could not able to achieve height  of this particle

**Comment by afhaider** [comment]
could u provide an example would appreciate it

**Comment by afhaider** [comment]
.wrapper {
    position: relative;
}

.xt{
    background-color: black;
    color: black;
    position: absolute;
    text-align: center;
    top: 40%;
    width: 100%;
}

<div className="wrapper">
    <Particles />
    <div className="xt">
        <h1>This is a test</h1>
    </div>
</div>

I am not getting the <particle > height it overlay work properly but i cannot able to increase or decrease its height

**Comment by matteobruni** [comment]
You can start from this sample: https://codesandbox.io/s/react-particles-js-masking-background-vz4eq?file=/src/App.js

Particles there uses 100% of height and width, but you can change the css file to have a different size.
If you use a % value or a relative value (`rem`, `em`, `vw`, `vh`, etc.) you'll se the `canvas` adjust itself on window resize.

If you have issues setting the height of the particles, this sample should help

**Comment by afhaider** [comment]
https://drive.google.com/file/d/1pkVJ2c_g870u4RK_YE2BR5D3XLGwcm6m/view?usp=sharing

section.tsparticles {
    width: 50%;
    height: '400rem';
   background-color: #1bb4d9;
    margin: 0;
    position: relative;
    padding: 0;
    top: 0;
    left: 0;
  }

sir ur code work fine and good 
but i want to achieve something <section className='tsparticles> <Particle....></section
i try multiple time it doesnt increase its height i put 300% etc px everything

**Comment by afhaider** [comment]
section.tsparticles {
    width: 100%;
    height: 300%;
   background-color: #1bb4d9;
    margin: 0;
   
    padding: 0;
  
  }
  #tsparticles {
    width: 200%;
    height: 300%;
  
  
  }
  <section className='tsparticles'>
<Particles
    params={{
	   
      particles: {
        number: {
          value: 80,
          density: {
            enable: true,
            value_area: 700
          }
        },
        color: {
          value: "#7bf"
        },
        shape: {
          type: "circle",
          stroke: {
            width: 0,
            color: "#000000"
          },
          polygon: {
            nb_sides: 5
          }
        },
        opacity: {
          value: 1,
          random: false,
          anim: {
            enable: false,
            speed: 1,
            opacity_min: 0.1,
            sync: false
          }
        },
        size: {
          value: 5,
          random: true,
          anim: {
            enable: false,
            speed: 40,
            size_min: 0.1,
            sync: false
          }
        },
        line_linked: {
          enable: true,
          distance: 150,
          color: "#ffffff",
          opacity: 0.4,
          width: 1
        },
        move: {
          enable: true,
          speed: 6,
          direction: "none",
          random: false,
          straight: false,
          out_mode: "out",
          bounce: false,
          attract: {
            enable: false,
            rotateX: 600,
            rotateY: 1200
          }
        }
      },
      interactivity: {
        detect_on: "canvas",
        events: {
          onhover: {
            enable: true,
            mode: "grab"
          },
          onclick: {
            enable: false,
            mode: "push"
          },
          resize: true
        },
        modes: {
          connect: {
            distance: 40,
            lineLinked: {
              opacity: 0.5
            },
            radius: 40
          },
          grab: {
            distance: 140,
            line_linked: {
              opacity: 1
            }
          },
          bubble: {
            distance: 400,
            size: 40,
            duration: 2,
            opacity: 8,
            speed: 3
          },
          repulse: {
            distance: 200,
            duration: 0.4
          },
          push: {
            particles_nb: 4
          },
          remove: {
            particles_nb: 2
          }
        }
      },
      retina_detect: true
	    
	}} /></section>

finally got it worked  thnx ur id help with class to extend both elements

**Comment by afhaider** [comment]
https://drive.google.com/file/d/1MdDFrmVjb811A-7I3j0UxFSFm_hJrDSR/view?usp=sharing
redux thunks - image array everything working fine o,o/ in redux thnx ur big help otherwise i would never achieve this

**Comment by afhaider** [comment]
might be my script broken give me 1day i need to re-fix everything then will type if it work or not in mobile view

**Comment by afhaider** [comment]
https://drive.google.com/file/d/15dLqEW8sv79gG_Pgb_3nw0ACKcDqZ0ZO/view?usp=sharing
everything working fine but in mobile view it go half
https://drive.google.com/file/d/1wk-GKSxQKSYOxFzgL6CmzD2fgTVktr36/view?usp=sharing

**Comment by afhaider** [comment]
at last i figure it out with ur help with that code i used on specific component 
#tsparticles {
    width: 100%;
 height: 80rem;
   color:#EB5757;
    position: absolute;
   
  }
  with this absolute it remain on specific component then i used it on any template and it show o,o/
https://drive.google.com/file/d/1bxNvnTlA9eOhtAxiNxBfpCrrstMpSt-k/view?usp=sharing  - worked many thanks @matteobruni
