### ISSUE TITLE
Full screen for particles.

### ISSUE THREAD

**Issue by trishantpahwa** [Wufe/react-particles-js#146]
Is there a way to create the canvas full screen and media responsive? Like a background?
Since, the height and width are props for the component, they remain fixed, I think.

How to make it dynamic. And scale with respect to window and screen size? Full screen on different devices of different screen-size, resolutions and, on resizing the window.

**Comment by matteobruni** [comment]
Hi @trishantpahwa 

Check out this CodeSandbox sample

https://codesandbox.io/embed/react-particles-js-masking-background-vz4eq

I’ve set a style in the CSS with the fixed position so the canvas acts like a background

**Comment by trishantpahwa** [comment]
https://stackoverflow.com/questions/62887690/how-to-make-particles-js-fullscreen-in-react

**Comment by trishantpahwa** [comment]
How to make it look like this?
![cool-background](https://user-images.githubusercontent.com/45137136/90122171-81b39500-dd7a-11ea-93d3-8dfdcfa9ab0e.png)

**Comment by trishantpahwa** [comment]
And do you have a discord server for this project?

**Comment by matteobruni** [comment]
Hi @trishantpahwa,

I'm not the maintainer of this project, I maintain the particles core library and that project has a slack that you can find in the readme: https://github.com/matteobruni/tsparticles#api-docs

If you need quick help for particles configuration it's the right place
