### ISSUE TITLE
Polygon not appearing

### ISSUE THREAD

**Issue by trishantpahwa** [Wufe/react-particles-js#147]
On adding the option to create a polygon using particles of an svg image. But, nothing appears.
These are the settings:
polygon: {
                            enable: true,
                            type: 'inside',
                            move: {
                                radius: 10
                            },
                            url: "/logo.svg"
                        }

The logo.svg is in the same directory of the react component that is calling the <Particles />

**Comment by matteobruni** [comment]
Hi @trishantpahwa,

The `polygon` options requires `"pathseg"` library in some browsers (Chrome is one of them)

You can fix that just with this

```javascript
import "pathseg";
```

You can checkout a CodeSandbox sample here: https://codesandbox.io/s/react-particles-js-masking-background-forked-vc3v2?file=/src/App.js

**Comment by garrud-trishant** [comment]
I am still not able to load the svg. :(

[Sandbox](https://codesandbox.io/s/still-rain-2lrnm?file=/src/App.js)
