### ISSUE TITLE
Can't get it to work, may be I'm making a mistake?

### ISSUE THREAD

**Issue by 96312** [Wufe/react-particles-js#152]
Hello all, I'm fairly new to react and want to use particles-js in my first learning project. This is my index and app JS files:

https://codesandbox.io/s/distracted-minsky-i1op8?file=/src/App.js

I have installed the package with npm install, yet nothing is getting rendered when I run it. What must I be doing wrong? :P 
If you can help me figure this out, I'd appreciate it. 

Please and thank you.

**Comment by matteobruni** [comment]
Hi @96312, The particles default color is white so you won't see anything because the background color is white too.

**Comment by 96312** [comment]
@matteobruni Hi! Oh wow, that was kinda silly on my part. I added a black background on my `index.css` and it works in a spectacular fashion. Thank you and sorry for the trouble.

ps: just to make sure I'm on the right track, that *is* the right way to define a background for the page on react as well, amirite? I've only dealt with simple html and css in the past so I relate everything to that.

**Comment by matteobruni** [comment]
You can use the `background` options in the particles if you prefer

You can find the documentation here: <https://particles.js.org/interfaces/_options_interfaces_background_ibackground_.ibackground.html>

This is the link with all the options available: <https://particles.js.org/interfaces/_options_interfaces_ioptions_.ioptions.html>

**Comment by 96312** [comment]
Thanks for linking it! I struggled with figuring out the hierarchy for a second, but it all worked out at the end. Thanks a ton for helping me figure this out @matteobruni
