### ISSUE TITLE
Changing the size of a type Character?

### ISSUE THREAD

**Issue by mattspahr** [Wufe/react-particles-js#155]
I am trying to make the size bigger when type is set to 'character' but nothing is happening. It seems to be fine with any other type. Am I missing something ?

`
particles: {

            number: {
              value: 50,
              density: {
                enable: true,
                value_area: 600,
              },
            },
            shape: {
              type: 'char',
              character: {
                value: '$',
              },
            },
            color: {
              value: theme.palette.secondary.main,
            },
            size: {
              value: 10,
              random: true,
              anim: {
                enable: true,
              },
            }
}
`

**Comment by matteobruni** [comment]
Hi @mattspahr,

I tried a config with chars and different size here: https://codepen.io/matteobruni/pen/xxGdyjd

But it seems to work like any other shape (which was the expected behavior).

Can you double-check the config to see if it's working for you too?

**Comment by jayp0521** [comment]
> I am trying to make the size bigger when type is set to 'character' but nothing is happening. It seems to be fine with any other type. Am I missing something ?
> 
> `
> particles: {
> 
> ```
>         number: {
>           value: 50,
>           density: {
>             enable: true,
>             value_area: 600,
>           },
>         },
>         shape: {
>           type: 'char',
>           character: {
>             value: '$',
>           },
>         },
>         color: {
>           value: theme.palette.secondary.main,
>         },
>         size: {
>           value: 10,
>           random: true,
>           anim: {
>             enable: true,
>           },
>         }
> ```
> 
> }
> `
I am also having this issue. Here is my config. Error only occurs with character. Rest work fine.
```js
const particlesParams: IParticlesParams = {
    interactivity: {
        events: {
            onHover: {
                enable: true,
                mode: 'repulse',
            },
            resize: true,
        },
    },
    particles: {
        line_linked: {
            enable: false,
        },
        collisions: {
            enable: true,
            mode: 'bounce',
        },
        number: {
            value: 60,
        },
        shape: {
            type: 'character',
            character: { value: [ '0', '1' ] },
        },
        color: {
            value: '#64ffda',
        },
        size: {
            value: 200,
            random: false,
        },
    },
}
```

**Comment by matteobruni** [comment]
I've found the issue

```javascript
        font: "Verdana",
        weight: "400",
        style: ""
```

These properties are required due to a bug that will be fixed soon, I've found that now 😅, as a workaround include them and everything works fine as expected
