### ISSUE TITLE
Is there a way to make sure you get one of each character from value array?

### ISSUE THREAD

**Issue by DitwanP** [Wufe/react-particles-js#158]
Like if I have 12 characters, I want every one of them to e displayed and not have it done randomly when I set the particle count to 12. Is there a way I could achieve this? I tried setting random to false under the shape property but that does not seem to work.

**Comment by matteobruni** [comment]
Hi @DitwanP,

You can do this configuration in two ways (at least):

- You can set particles manually, using the `manualParticles` property. You can find documentation [here](https://particles.js.org/interfaces/_options_interfaces_imanualparticle_.imanualparticle.html)

- You can reduce duplicates, this goes sequentially when initializing a particle. You can find documentation [here](https://particles.js.org/interfaces/_options_interfaces_particles_iparticles_.iparticles.html#reduceduplicates) (sorry, I forgot to add it to the table, but the property goes inside the `particles` section)

**Comment by DitwanP** [comment]
Tanks for the fast response!
