### ISSUE TITLE
Support child components

### ISSUE THREAD

**Issue by Josephmaxim** [Wufe/react-particles-js#16]
Would be nice to support child components since using CSS absolute method doesn't trigger mouse hover on particles when you have another component blocking it. adding `pointer-events: none;` will remove scroll effect.

```
<Particles>
    <div>Hello World</div>
</Particles>
```

**Comment by Wufe** [comment]
To move a div over a canvas element, position: absolute is required. Adding child components would result in a div with absolute position containing all the children.
The effect would be the same.

**Comment by Josephmaxim** [comment]
Div with position: absolute; with user-select & pointer-events set to none does the trick.
