### ISSUE TITLE
Advantage over tsparticles/react

### ISSUE THREAD

**Issue by FBosler** [Wufe/react-particles-js#160]
Heya,

big fan of standardization here. I am wondering, what exactly is the advantage of react-particles-js over [react-tsparticles](https://github.com/matteobruni/tsparticles/blob/master/components/react/README.md)

Cheers

**Comment by matteobruni** [comment]
They use the same core library, this library has different default values but they are both updated regularly with the latest tsParticles versions.
This library is owned by another dev so updates needs his approval, so some updates could have some delay.

**Comment by FBosler** [comment]
@matteobruni thx for the response. I took a closer look, it seems they pretty much have feature parity, except from "polygon-mask".

Cheers
