### ISSUE TITLE
Can't resolve './cjs/particles' for version 3.4.1

### ISSUE THREAD

**Issue by mafiusu** [Wufe/react-particles-js#162]
I recently updated the package to version 3.4.1 and found an error.

In index.js at the first line for ReactParticles there is a require to a non-existent path ./cjs/particles/

```
const ReactParticles = require('./cjs/particles');
for (let key in ReactParticles) {
    ReactParticles.default[key] = ReactParticles[key];
}
module.exports = ReactParticles.default;
```

**Comment by matteobruni** [comment]
The `cjs` folder is created after the package build, the npm package has it.
If you have downloaded the sources you need to build it first.
