### ISSUE TITLE
Can't perform a React state update on an unmounted component. 

### ISSUE THREAD

**Issue by artpumpkin** [Wufe/react-particles-js#163]
> Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.

Only happens at the first unmount, not sure why, but I'm basically using a templating system, which requires switching between 2 or more components as templates.

**Comment by matteobruni** [comment]
Hi @artpumpkin,

Can you share a reproducible sample?
