### ISSUE TITLE
[Bug] TypeError: Cannot read property 'circle' of undefined in Next.JS

### ISSUE THREAD

**Issue by JaeWangL** [Wufe/react-particles-js#167]
I'm working this library with next.js

```
    "next": "10.0.5",
    "react": "^17.0.1",
    "react-particles-js": "^3.4.1",
```

```
      <Particles
        params={{
          particles: {
            number: {
              value: 160,
              density: {
                enable: false,
              },
            },
            size: {
              value: 3,
              random: true,
              anim: {
                speed: 4,
                size_min: 0.3,
              },
            },
            line_linked: {
              enable: false,
            },
            move: {
              random: true,
              speed: 1,
              direction: 'top',
              out_mode: 'out',
            },
          },
          interactivity: {
            events: {
              onhover: {
                enable: true,
                mode: 'bubble',
              },
              onclick: {
                enable: true,
                mode: 'repulse',
              },
            },
            modes: {
              bubble: {
                distance: 250,
                duration: 2,
                size: 0,
                opacity: 0,
              },
              repulse: {
                distance: 400,
                duration: 4,
              },
            },
          },
        }}
      />
```

But when I run my app 
package says **"TypeError: Cannot read property 'circle' of undefined"**

**Comment by traubas** [comment]
me too. it worked until today. been working with it for the last 1 year.

**Comment by matteobruni** [comment]
Hi @JaeWangL and @traubas,

You can fix that installing `tsparticles@1.19.2`. I made a change in `1.19.3` that broke this package. I’ll fix it ASAP.

Sorry for the inconvenience

**Comment by JaeWangL** [comment]
> Hi @JaeWangL and @traubas,
> 
> You can fix that installing `tsparticles@1.19.2`. I made a change in `1.19.3` that broke this package. I’ll fix it ASAP.
> 
> Sorry for the inconvenience

This work!! Thank you~~

**Comment by Ayoubho22** [comment]
is it like npm install tsparticles@1.19.2 ??
I'm new to React, anyway when I run the command nothing change it's still giving me the error 'TypeError: Cannot read property 'circle' of undefined' 
thanks in advance

**Comment by GitGitBoom** [comment]
@Ayoubho22 you need to replace the sub-dependency. In yarn you can use resolutions. Npm is a bit more of a pain. 

Yarn: https://classic.yarnpkg.com/en/docs/selective-version-resolutions/

NPM: https://stackoverflow.com/questions/15806152/how-do-i-override-nested-npm-dependency-versions

Thanks @traubas for the quick support.

**Comment by matteobruni** [comment]
I released `1.19.4` with the bug fix. Everything should be fine now.

**Comment by RilleMichi** [comment]
Hi @GitGitBoom 

Can you maybe write it down (with yarn)? I tried, but it didn't work. Thanks in advanced. 
Im also just a beginner :)

**Comment by matteobruni** [comment]
@RilleMichi just update the `tsparticles` dependency and you're done

**Comment by lindelof** [comment]
> Hi @JaeWangL and @traubas,
> 
> You can fix that installing `tsparticles@1.19.2`. I made a change in `1.19.3` that broke this package. I’ll fix it ASAP.
> 
> Sorry for the inconvenience

Please respect the achievements of others. I really don’t like your approach, and all kinds of ads on github

**Comment by Wufe** [comment]
@lindelof
tsparticles is not an advertised library, but a dependency of react-particles-js.
@matteobruni is the creator of tsparticles, so listen to him

**Comment by UmarFaruqueN** [comment]
any solutions??
