### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by Mast0john** [wufe/react-particles-js#169]
I have this error since yesterday 

Error:(8, 27) TS2307: Cannot find module 'tsparticles/dist/Core/Container'.
Error:(9, 34) TS2307: Cannot find module 'tsparticles/dist/Types/RecursivePartial'.
Error:(10, 26) TS2307: Cannot find module 'tsparticles/dist/Options/Interfaces/IOptions'.
Error:(11, 37) TS2307: Cannot find module 'tsparticles/dist/Plugins/PolygonMask/PolygonMaskPlugin'.
Error:(12, 34) TS2307: Cannot find module 'tsparticles/dist/Plugins/Absorbers/AbsorbersPlugin'.
Error:(13, 33) TS2307: Cannot find module 'tsparticles/dist/Plugins/Emitters/EmittersPlugin'.
Error:(17, 15) TS2307: Cannot find module 'tsparticles/dist/Enums'.
Information:File is not included in any tsconfig.json

With this file..

// Type definitions for react-particles-js v3.0.0
// Project: https://github.com/wufe/react-particles-js
// Definitions by: Simone Bembi <https://github.com/wufe>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

/// <reference types="react" />
import { ComponentClass } from "react";
import { Container } from "tsparticles/dist/Core/Container";
import { RecursivePartial } from "tsparticles/dist/Types/RecursivePartial";
import { IOptions } from "tsparticles/dist/Options/Interfaces/IOptions";
import { IPolygonMaskOptions } from "tsparticles/dist/Plugins/PolygonMask/PolygonMaskPlugin";
import { IAbsorberOptions } from "tsparticles/dist/Plugins/Absorbers/AbsorbersPlugin";
import { IEmitterOptions } from "tsparticles/dist/Plugins/Emitters/EmittersPlugin";

export type IParticlesParams = RecursivePartial<IOptions & IPolygonMaskOptions & IAbsorberOptions & IEmitterOptions>;

export * from 'tsparticles/dist/Enums';

export interface ParticlesProps {
    width?: string;
    height?: string;
    params?: IParticlesParams;
    style?: any;
    className?: string;
    canvasClassName?: string;
    particlesRef?: React.RefObject<Container>;
}

type Particles = ComponentClass<ParticlesProps>;

declare const Particles: Particles;
export default Particles;

Any idea ?

**Comment by RobbyB97** [comment]
I'm having the same issue on Linux, but not Windows

**Comment by jemxz** [comment]
instead of using react-particles-js use react-tsparticles(it is another package) this works perfectly

**Comment by jothamardel** [comment]
`./node_modules/react-particles-js/cjs/particles.js
Module not found: Can't resolve 'tsparticles' in 'C:\Users\Bee\Documents\side-projects\face-detection\node_modules\react-particles-js\cjs'`

**Comment by ElhadiRagabaat** [comment]
./node_modules/react-particles-js/cjs/particles.js
5:59:29 PM: Cannot find module: 'tsparticles'. Make sure this package is installed.

**Comment by hotcakedev628** [comment]
I am having the same issue.
```
Generating development JavaScript bundle failed

Can't resolve 'tsparticles/Plugins/PolygonMask/Enums' in 'E:\work\personal\portfolio-davidyang\node_modules\react-particles-js\cjs'

If you're trying to use a package make sure that 'tsparticles/Plugins/PolygonMask/Enums' is installed. If you're trying to use a local file make sure that the path is correct.

File: node_modules\react-particles-js\cjs\particles.js

failed Re-building development bundle - 3.331s
```
