### ISSUE TITLE
Benefits compared to tsparticles official react lib

### ISSUE THREAD

**Issue by RemyMachado** [wufe/react-particles-js#170]
Hello, I couldn't find the answer, so I'll ask :

- ### What are the benefits of using this library rather than using `react-tsparticles` ?

`react-tsparticles` being the official react package of `tsparticles` (that `react-particles-js` is relying on).

Thanks in advance for your response.

**Comment by garrettseward** [comment]
This project, `react-particles-js`, uses a typescript wrapper that **already provides** a react component. Additionally, the version pinned in this project is out of date with the latest typescript wrapper version. That means it has an older version of the core particles library.

I've had issues getting this project to work that seem to be related to it having an old version of `tsparticles` which in turn means an older version of the core library.

I just switched to the react component in `react-tsparticles` and it works great. @RemyMachado I recommend to use that, then you only have to worry about that `tsparticles` staying up-to-date, as opposed to a second layer of dependences by using this project (`react-particles-js`).

**Comment by Wufe** [comment]
I'm indeed planning to deprecate this library in favor of react-tsparticles
