### ISSUE TITLE
Canvas stretches particles until resize

### ISSUE THREAD

**Issue by Jhappy77** [wufe/react-particles-js#175]
The canvas starts at a default height. Any CSS selectors that set the height to 100% only stretch the particles, not change the height attribute of the canvas. Once I resize my window, everything works as intended, but it is horribly stretched until the window is resized for the first time and the canvas size recalculates. 

Is there any way to force the canvas size to recalculate immediately? I don't want this stretch effect
![image](https://user-images.githubusercontent.com/45266424/116317609-ce0bfd00-a770-11eb-8f71-d8aff56ff445.png)
Initial stretched version (upon reloading site). The canvas has a height attribute of 575, the particles appear as if the canvas was 575px but are stretched to fit the full content.

After resizing the window, the canvas height goes to 100% of parent div like it should, and everything works as intended
![image](https://user-images.githubusercontent.com/45266424/116317718-f3990680-a770-11eb-9e21-3bd6e4003228.png)

**Comment by KeithReshma** [comment]
Hi ,

Use this Code in the component where u are importing particles 

  useEffect(() => {
    // dispatch it once mounted
    setTimeout(
      ()=>{window.dispatchEvent(new Event('resize'));},
      1000
      );
  }, []);
