### ISSUE TITLE
Cannot find module 

### ISSUE THREAD

**Issue by Hazza88** [Wufe/react-particles-js#182]
When starting my app I get the error:
Error: Cannot find module 'tsparticles/dist/Options/Classes/Options'

Any idea why?
"react-particles-js": "^3.5.1"

**Comment by matteobruni** [comment]
Downgrade the package tsparticles to 1.29.2 for now, the update is requested #181

**Comment by Hazza88** [comment]
Thanks that worked :)

**Comment by Wufe** [comment]
Fixed with v3.5.2

**Comment by gujiwuqing** [comment]
> Fixed with v3.5.2

3.6.0又开始报错了

The same error occurred
