### ISSUE TITLE
Unable to use react-particles-js due to tsparticles dependency.

### ISSUE THREAD

**Issue by bharathcs** [Wufe/react-particles-js#183]
## Bug

After installing react-particles-js and its dependencies, it should be able to compile and run. Instead it crashes, with the following:

> Failed to compile
> 
> ./node_modules/react-particles-js/cjs/particles.js
> Module not found: Can't resolve 'tsparticles/dist/Enums' in '/Users/bhcs/dedoco/test/node_modules/react-particles-js/cjs'
> 
> This error occurred during the build time and cannot be dismissed.

## Version information

```javascript
// dependencies from package.json
  "dependencies": {
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-particles-js": "^3.5.1",
    "react-scripts": "4.0.3",
    "web-vitals": "^1.0.1"
  },

// tsparticle peer dependency from package-lock.json
    "node_modules/tsparticles": {
      "version": "1.30.0",
      "resolved": "https://registry.npmjs.org/tsparticles/-/tsparticles-1.30.0.tgz",
      "integrity": "sha512-+f+SaSrT213mbH3+nm7kXr6e8STULZdu3ZYsn4rLmneCz3MA7VdqsFaqlQvVFsQef2Xxhunna1umXbSErZ79IQ==",
      "hasInstallScript": true,
      "peer": true,
      "funding": {
        "type": "github",
        "url": "https://github.com/sponsors/matteobruni"
      },
      "optionalDependencies": {
        "pathseg": "^1.2.0"
      }
    },
```

## Reproducible Steps:

1. Clone this repo: https://github.com/bharathcs/minimum-test-reactparticles
2. `npm install && npm start`

**Comment by bharathcs** [comment]
Original error:
<img width="1254" alt="image" src="https://user-images.githubusercontent.com/7360964/123734341-bd424980-d8cf-11eb-93f9-95e2b830aff8.png">

After explicitly installing the tsparticles dependency:
<img width="1243" alt="image" src="https://user-images.githubusercontent.com/7360964/123734364-ca5f3880-d8cf-11eb-8506-713419d92b07.png">

**Comment by Wufe** [comment]
Upgrade react-particles-js to version 3.5.2 (released just now).

**Comment by bharathcs** [comment]
Hi Wufe, thanks for the really quick response, but unfortunately its still not working for me after updating:
https://github.com/bharathcs/minimum-test-reactparticles/tree/react-particles-js-3-5-2

Now I get a blank page:
<img width="1268" alt="image" src="https://user-images.githubusercontent.com/7360964/123736061-ff20bf00-d8d2-11eb-8d86-df175c941a3a.png">

**Comment by Wufe** [comment]
My bad, I've not updated the peer dependency. For now you can manually add tsparticles with `npm install -D tsparticles`.

**Comment by bharathcs** [comment]
Hmm I'm not sure why but it still doesn't work for me
(v 3.5.3: https://github.com/bharathcs/minimum-test-reactparticles/tree/react-particles-js-3-5-2 )

**Comment by Wufe** [comment]
I got it running:
- I added tsparticles via `npm install --save tsparticles` (it's a peer-dependency)
- Changed the background to black

If it doesn't work for you, ensure tsparticles in your package-lock.json is always 1.30.0 or above (I just deleted the package-lock.json, the node_modules folder, and did a `npm install`)

<img width="1276" alt="Screenshot 2021-06-29 at 08 26 03" src="https://user-images.githubusercontent.com/7671694/123748315-595e5780-d8b4-11eb-9923-558113bb6f6e.png">

**Comment by bharathcs** [comment]
Ahhh okay, got it, sorry about that! Yep 3.5.3 works now!
