### ISSUE TITLE
Particles Disappear When Page Is Refreshed

### ISSUE THREAD

**Issue by ghost** [wufe/react-particles-js#192]
If I comment, save, un-comment and save again, my particles component works. But if I refresh the page the particles disappear. 

My component looks like this:

`<Particles params={particlesConfig} />`

**Comment by badrkamel** [comment]
> If I comment, save, un-comment and save again, my particles component works. But if I refresh the page the particles disappear.
> 
> My component looks like this:
> 
> `<Particles params={particlesConfig} />`

same

**Comment by devotii** [comment]
I've the same issue

**Comment by JackwillJudge** [comment]
has anyone found a fix to this one yet?

**Comment by sylwiawajgel** [comment]
You can try a workaround and load particles after some time, using `setTimeout`. It works for me. Not a good solution, but better than nothing, until it will be fixed.

```
const [showParticles, setShowParticles] = useState(false);
  
  useEffect(() => {
    setTimeout(() => {
      setShowParticles(true);
    }, 500);
  }, []);

  return (
     <>
         {showParticles && (
              <Particles/>
         )}
    </>
  );
```

**Comment by JackwillJudge** [comment]
awesome thanks that worked
