### ISSUE TITLE
Particles "explosion" on load

### ISSUE THREAD

**Issue by jordykoppen** [Wufe/react-particles-js#2]
Currently i'm using this package in some of my projects. Everywhere i use this i get this sort of "exploding" pack of particles. Am I doing something wrong or is this a bug?
No matter my config it happens with all of them.

[Example](https://gfycat.com/ShockedTerribleDodo)

If you want me to provide more information let me know!
Thanks.

**Comment by Wufe** [comment]
Can you post the parameters you use and the size of the canvas?
