### ISSUE TITLE
Gatsby + Particles

### ISSUE THREAD

**Issue by patrykmat** [Wufe/react-particles-js#23]
Hi,
I am trying to run the simple possible example of Particles with Gatsby, and It seems to not work for any combination. My index file looks like:

```
import React from "react"
import Particles from 'react-particles-js';


export default () => (
    <div>
        <Particles/>
    </div>
);
```

I can see that the canvas is added into DOM, but nothing is shown. Is it a correct approach?

React version: 16.2.0
Gatsby version: 1.9.207
Particle version: 2.1.0

**Comment by LunarBiscuit** [comment]
I am also having this problem.

Locally, running gatsby develop is fine, and this works without an issue, however when you build and deploy to Netlify or similar platforms, it does not seem to work - perhaps something to do with the build/bundle process?

**Comment by blaskovicz** [comment]
I'm not using Gatsby, but i'm having a similar issue via `create-react-app`. I just get an empty canvas with no javascript errors nor build errors.

**Comment by Wufe** [comment]
Did you change color of the particles? Without params the canvas renders white particles ( not visible with a white background ).

Checkout this minimalistic example, it is based on a create-react-app layout:
[![Edit vy3k5w2k17](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vy3k5w2k17)

**Comment by wdavidw** [comment]
It work for me:
react 15.6.2
gatsby 1.9.259
particles.js 2.0.0

**Comment by OR13** [comment]
same here, with versions above ^

**Comment by veksen** [comment]
It works for me on Gatsby and I'm deployed on Netlify. Sample, minimal code:

```
"gatsby": "^1.9.247",
"particles.js": "^2.0.0",
"react-particles-js": "^2.1.3"
```

```
import React from 'react'
import { css } from 'emotion'
import Particles from 'react-particles-js'

const heroStyles = css`
  background: linear-gradient(#001d43 0%, rgba(0, 29, 67, 0) 75%), #0f5783;
  color: #fffbf7;
  position: relative;
`

const particlesStyles = css`
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
`

const Hero = () => (
  <div className={heroStyles}>
    <Particles
      className={particlesStyles}
      params={{
        particles: {
          move: {
            speed: 3,
          },
        },
      }}
    />
  </div>
)
export default Hero
```

**Comment by RobertoMSousa** [comment]
It's working here, check my repo to see how I did it.
https://github.com/RobertoMSousa/gatsbyjs_hello_world

**Comment by avocadoras** [comment]
Hi, is there a way to add it in the background?

**Comment by avocadoras** [comment]
nvm I was able to do it 😳

**Comment by avocadoras** [comment]
@RobertoMSousa thanks

**Comment by jilliankeenan** [comment]
I had a look at @RobertoMSousa and my code is doing the same, I can get the particles to render but they aren't responsive on mouse hover when using Gatsby? Is there a resolve for this?

**Comment by Wufe** [comment]
@jilliankeenan I might guess there's something in front of the canvas, or the position of the canvas itself is not set to be relative.

I suggest you to check the library's [demo code](https://github.com/Wufe/react-particles-js-demo) or this [sandbox](https://codesandbox.io/s/ypzr371l29) where you can fork the code, modify it and send back to this conversation.

**Comment by arhoy** [comment]
You might see a white canvas because the particles themselves are also white. Try going to inspecting the canvas element and seeing if it is rendered there and changing the background to black.

**Comment by lindelof** [comment]
Of course you can also use this library
https://github.com/lindelof/particles-bg

**Comment by Mayron** [comment]
Not working for me. It looks great in `gatsby develop` but breaks in `gatsby build`.
