### ISSUE TITLE
.vscode folder

### ISSUE THREAD

**Issue by jay-bricksoft** [Wufe/react-particles-js#26]
it seems that you use visual studio code, with settings for this project.
it would be an improvement committing this folder since we could work with the same tooling and settings.

these settings could still be overriden per-user but provide a general code-style and toolchain

**Comment by jay-bricksoft** [comment]
#27

**Comment by Wufe** [comment]
I usually set only one rule: ignore node_modules.
I'm not sure this would be useful for someone else.

**Comment by Wufe** [comment]
No updates for a while. Closing.
