### ISSUE TITLE
TypeScript error, no declaration file for module

### ISSUE THREAD

**Issue by raptoria** [Wufe/react-particles-js#3]
(6,28): error TS7016: Could not find a declaration file for module 'react-particles-js'. '/Users/clacey/caprona-ui/client/node_modules/react-particles-js/lib/particles.js' implicitly has an 'any' type.

**Comment by Wufe** [comment]
The typescript type definition is not available.
Try to use this instead:
```
const ParticlesLibrary = require( 'react-particles-js' );
const Particles = Particles.default;
```

and use it as usual `<Particles />`.

**Comment by Wufe** [comment]
With version v1.5.0 a data definition for typescript has been added.
You can now use:

```js
import Particles from 'react-particles-js';
```

Please upgrade react-particles-js to v1.5.0.

**Comment by raptoria** [comment]
thanks!
