### ISSUE TITLE
Custom shape image

### ISSUE THREAD

**Issue by wdavidw** [Wufe/react-particles-js#34]
Is there any mecanisme/hook to generate custom images. My use case would be to insert random SVG inside shapes. Thank you for your work!

**Comment by Wufe** [comment]
I'm afraid at the time of writing it is not possible.
It would require a different approach on particles lifetime handling (e.g. representation of particles through "renderer" functions or jsx elements) therefore a complete reimplementation of the core concept of the library itself.
I've thought something like this before, but I don't have time at the moment for this huge refactoring.

**Comment by wdavidw** [comment]
I've been having a second thought about it. Instead of accepting an image object, we could accept either an object or an array of object. This way, it would be backward compatible, easy to implement while fitting my usecase. I could help you in this but first I need to find a way to have svg displayed which is not the case at the moment.

**Comment by wdavidw** [comment]
Closing since their is now the issue #40 with a pull request
