### ISSUE TITLE
shape type star cant work

### ISSUE THREAD

**Issue by fuad-ardiono** [Wufe/react-particles-js#41]
This is my code.
<img width="610" alt="screen shot 2018-05-31 at 13 34 37" src="https://user-images.githubusercontent.com/19608528/40763393-62f9792c-64d7-11e8-8ed6-749e0523520c.png">

This is result of my code
<img width="1440" alt="screen shot 2018-05-31 at 13 34 54" src="https://user-images.githubusercontent.com/19608528/40763411-72ebd096-64d7-11e8-93ef-5cf5299703a6.png">

My expectation the shape return star

**Comment by Wufe** [comment]
You forgot the object "particles" under "params".

Check this out: [CodeSandbox](https://codesandbox.io/s/k9z2pmn2mo)
