### ISSUE TITLE
Multiple Images

### ISSUE THREAD

**Issue by JohnDun89** [Wufe/react-particles-js#42]
Hey thanks for creating the awesome library. 

Is it possible to add multiple Images? I saw options in the library for 'images'  but I'm not sure how to include them in the JSON object. 

I have tried including the following: 

 images: { ["imageone", "imagetwo"] }

but it doesn't seem to work

**Comment by Wufe** [comment]
Wondering if @wdavidw can provide some help here 🤣

**Comment by wdavidw** [comment]
Hi @JohnDun89, images expect an array, not an object:

```js

images: [
  {
    src: your_url,
    width: 50,
    height: 50,
  },{
    ...
  }
]
```

**Comment by wdavidw** [comment]
This issue might be closed if considered resolved.

**Comment by Wufe** [comment]
Closing this issue.
