### ISSUE TITLE
Should create component with PureComponent

### ISSUE THREAD

**Issue by LucienLee** [Wufe/react-particles-js#46]
For the performance improvement, I suggest that replace `React.Component` with `React.PureComponent`. Otherwise, check props in `shouldcomponentupdate`, don't update when props is the same.

**Comment by Wufe** [comment]
At the moment the main component is a component which calls a library's refresh only after a shallow props comparison. It is the same behavior of a pure component, so there's no overhead.
Also, the main particles component cannot have children, so even if the component gets re-rendered and if the props are the same, it does not refresh.
But nevertheless, the comparison is a best practice to be placed inside a shouldComponentUpdate, so thanks for your advice, I'll consider using a PureComponent (or a shallow compare in shouldComponentUpdate).
