### ISSUE TITLE
 'canvas' / 'repulse' is not defined   no-undef

### ISSUE THREAD

**Issue by muravitsky** [Wufe/react-particles-js#52]
Hello!
Thank you so much for so beautiful react module!
I'm using it on my study project now.
Unfortunately I can't use the "Interactivity" parameter  :(
It looks this way in my code: 
![image](https://user-images.githubusercontent.com/36592189/43989529-41583172-9d54-11e8-9e25-dc276fec3569.png)
And I got this error:
![image](https://user-images.githubusercontent.com/36592189/43989534-5bb07872-9d54-11e8-9e42-d53e540ca72c.png)
Other Particles features are already  works perfect.
Can you kindly help me with this issue? How I can enable Particles Interactivity in me React App?
Thank you in advance!

**Comment by Wufe** [comment]
Hi!
You need to specify them as strings:

`detect_on: "canvas"`, `mode: "repulse"`

**Comment by muravitsky** [comment]
@Wufe, thank you for your reply!
Actually, I have tried to use this parameters as a string.
It's compiled successfully but still nothing happens on the webpage when I try to use this beautiful `onhover ` or `onhlick` effect.
Here is my full list of parameters:
![image](https://user-images.githubusercontent.com/36592189/43990994-655f7d56-9d6c-11e8-9b1f-83215dfd7a1c.png)
And I rendering Particles this way:
`<Particles className='particles' params = {ParticlesOptions}/>`
Just no hover effect :(

**Comment by Wufe** [comment]
Hi @muravitsky , the params object is not correct: you nested "interactivity" into "particles".

Check this example:  
[![Edit Minimal repulse](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2oqznovmjn)

**Comment by muravitsky** [comment]
Thank you so much! It works! And it's just because of my inadvertence.
Thank you so much one more time!

**Comment by Wufe** [comment]
You are welcome 😁
