### ISSUE TITLE
react-particles-js can not working!!!

### ISSUE THREAD

**Issue by godspeedgld** [Wufe/react-particles-js#57]
my step is follow 

 1 create react project by create-react-app 
 2 npm install react-particles-js
 3 import  libs
    import Particles from 'react-particles-js'; 
4 add  components 
            <Particles />

But,  the page is blank  after i start page by npm start.

By the way. I try the demo of  react-particles-js.  the demo is OK
But the react project is still no working even I import sass file and  component ParticaleContainer.

How can I merge the react-particles-js into the react-project created by create-react-app??
thanks @Wufe

**Comment by Wufe** [comment]
Without a reproducible code base I cannot deduce what's wrong with the process.

Check this minimal demo: [CodeSandbox](https://codesandbox.io/s/4j3v5w077w)
