### ISSUE TITLE
Different appearence when using the Component compared to the JS Library

### ISSUE THREAD

**Issue by Stophface** [Wufe/react-particles-js#65]
Looking at this example 
[https://codepen.io/anon/pen/YREMLO](https://codepen.io/anon/pen/YREMLO) there are only a few lines/dots.

When I use the same params in the react component 

```
<Particles
    params={{
        "particles": {
            "number": {
                 "value": 80,
                 "density": {
                      "enable": true,
                          "value_area": 1000
                  }
            },
       },
  "retina_detect": true
}} />

```

it looks like this  [https://imgur.com/a/zjzZbXF](https://imgur.com/a/zjzZbXF).

There are way more lines connecting the dots. 
Why is that?

**Comment by Wufe** [comment]
This bug has been fixed in v2.4.1
