### ISSUE TITLE
Can't able to place another elements inside particles component.

### ISSUE THREAD

**Issue by nasr18** [Wufe/react-particles-js#68]
I wanna place some components inside particles component. Whatever the elements i add inside particles, not at all displaying.

**Comment by 13it235** [comment]
I have a similar issue. I want to use particle js as my background. I am trying to render a button over it and it does not appear. If I enclose the particle js component and button inside a div tag, they are arranged one below the other.

**Comment by Wufe** [comment]
As stated [here](https://github.com/Wufe/react-particles-js/issues/16) (#16), the Particles elements does not accept children due its composition: it is a simple canvas.
You can place components on top of the canvas by declaring its position to be absolute.

Check [this example](https://codesandbox.io/s/l909x87lr7).

**Comment by nasr18** [comment]
Yeah I fixed it by moving particles component to bottom. But my question is, why it's allowing other components placed below this component?

**Comment by r33fyello** [comment]
One way to do it example:
`<Fragment>
    <div
      className="container"
      style={{ width: '100%', height: '100vh', position: 'relative'}}
    >
      <Particles
        params={particleConf}
        style={{ width: '100%', position: 'absolute', zIndex: '-1' }}
      />
      <div className="navbar">
        <Navigation />
      </div>
      <hr />
      {children}
    </div>
  </Fragment>`
