### ISSUE TITLE
How to use in Next.js?

### ISSUE THREAD

**Issue by hrahimi270** [Wufe/react-particles-js#69]
Hello guys.
I love what you did! It's awesome.
Now I want to use it my Next.js project and it's getting hard for me!
Because in Next.js configs are hard!

Right now, I'm installed `react-particles-js` and run the simple example very successfully.
But when I want to use `polygon` example, I have some issues.
So I need your help.

### How to use `pathseg` in React/Next ?
This is my code:
**pic1**
![1](https://user-images.githubusercontent.com/38007163/50405085-d6308800-07c4-11e9-9fcf-8c2cb9bc6769.PNG)

**pic2**
![2](https://user-images.githubusercontent.com/38007163/50405087-dcbeff80-07c4-11e9-82cb-4ce16061db93.PNG)

I'm using polygon example just like that.
But I have no result.
I think it's because that I'm not using `pathseg`. How to use it? Any solution?
Very very tanks.
Regards, Hossein.

**Comment by Wufe** [comment]
I never used Next.js, however I think you may want to read [this section](https://github.com/zeit/next.js#populating-head) of the documentation about populating head.
Just put the pathseg polyfill link there.

**Comment by Wufe** [comment]
I'm afraid this is not possible at the moment.  
This would require a completely different approach.  
Nevertheless I will think about it because it's an interesting effect.  
Thanks for your feedback.

Closing this issue anyway, answers related to original question given.

**Comment by prettydev** [comment]
I'm using this on the next.js project, and works perfectly!
[https://github.com/tim-soft/react-particles-webgl](url)

**Comment by matteobruni** [comment]
This is the solution for Next.js https://github.com/matteobruni/tsparticles/issues/686

**Comment by Hamzasaeed-WpCorporate** [comment]
this is also one alternative option, https://nextparticle.nextco.de/
