### ISSUE TITLE
Render particles to canvas with specific id

### ISSUE THREAD

**Issue by gastongouron** [Wufe/react-particles-js#7]
Hello, and thanks for your lib. 
I'm currently trying webpack2/jsx and so far everything works as expected expect I cannot find a way to to understand how you apply this Particles to a specific element. Do you have any example of the implementation that goes a little deeper than: 

```
import Particles from 'react-particles-js';
 
class App extends Component{
  
    render(){
        return (
            <Particles params={{
            		particles: {
            			line_linked: {
            				shadow: {
            					enable: true,
            					color: "#3CA9D1",
            					blur: 5
            				}
            			}
            		}
            	}}/>
        );
    };
 
}
```
My problem is that I have a component with a canvas (it can be any other html tag) and I'd like to apply the effect on this specific canvas but cannot find a way... 

Thanks in advance for your help

**Comment by Wufe** [comment]
This is a react component: it provides a canvas in which all the particles are rendered.
If you are trying to enable particles on a particular canvas, you should try the [original version of particles.js](https://github.com/VincentGarreau/particles.js/).

I can help you exposing a loaded event callback ( like `canvasLoaded: (canvas: HTMLCanvasElement) => void` ) that gets called only when the canvas itself is loaded, and has the canvas as argument. It would permit you to manipulate the component-created canvas itself, but not make particles run on a particular one.

Let me know if you might need it.

**Comment by Wufe** [comment]
No comments for 3 months. Closing the issue.
