### ISSUE TITLE
Polygon URL issue

### ISSUE THREAD

**Issue by jp-signum** [Wufe/react-particles-js#81]
Having used both particle.js and your library before, I can not seem to get the URL component of my polygon params to correctly locate my svg I have tried putting it and changing the path to almost everything I can think of. Here are the errors from the console:

<img width="862" alt="Screen Shot 2019-03-09 at 6 50 29 AM" src="https://user-images.githubusercontent.com/15091817/54071218-ac212a80-4237-11e9-8591-9c94b64e3601.png">

This was me testing the url route: 
"/jp_poygon_singlePath.svg"  
as its at the root of my project ... I have tried to fetch it from numerous other places as well. Please help.

Things that may be affecting it:
react-router ? although the canvas is showing up correctly in the desired location

https://github.com/jp-signum/jp_sig_reactv1.git is the repository

**Comment by Wufe** [comment]
You have to serve the svg file in a **public folder**:
is http://localhost:3000/jp_polygon_singlePath.svg accessible navigating from the browser ? If not, the script cannot download the svg.

**Comment by jp-signum** [comment]
ahhhhh I see after moving it to my public folder and readjusting the url it now seems to be accessing the svg correctly however nothing is drawing on the canvas. I have removed all styling and anything I can think of from the parent components and container yet it does not seem to be working. Any suggestions on how to debug this? I am assuming its the svg ? I have the script in the body of my body

**Comment by Wufe** [comment]
First try a minimal particles settings, then adjust the css (it may be possible that white particles are rendered upon white background, thus they are not visible). After you got a minimal template, proceed with the svg polygon.

**Comment by jp-signum** [comment]
when starting with a minimal setting I get this error

<img width="752" alt="Screen Shot 2019-03-09 at 7 54 26 AM" src="https://user-images.githubusercontent.com/15091817/54071876-de835580-4240-11e9-8b47-56cf5a5b9287.png">

**Comment by jp-signum** [comment]
hey looks like i was able to figure it out thanks for the help

**Comment by jp-signum** [comment]
sorry have you ever seen anything like this happen ? and do you know where this might originate

<img width="227" alt="Screen Shot 2019-03-09 at 8 18 52 AM" src="https://user-images.githubusercontent.com/15091817/54072108-1f309e00-4244-11e9-92da-4e6d84e66e1c.png">

obviously those static lines arent supposed to be there

**Comment by Wufe** [comment]
Open your file with a svg editor and check if the path is correct

**Comment by jp-signum** [comment]
yeah I made it in adobe illustrator, after trying a few different things I realized there were some transforms being added and I was able to remove them before exporting the svg because simply deleting them from the svg code didnt solve the problem. I was able to do this by using the reset bounding box property in AI  ...... just in case anyway has a similar issue.

Thanks for answering quickly and helping me out !!!! much appreciated :)

**Comment by ambwani** [comment]
Hi, @jp-signum! I am having the exact same issues as you. May I know how you were able to solve it? Thanks in advance!

**Comment by jp-signum** [comment]
@ambwani what issue is that?
