### ISSUE TITLE
Error on page redirect

### ISSUE THREAD

**Issue by selimyalcin** [Wufe/react-particles-js#83]
The destroy function starts to fail after react 16

**Comment by selimyalcin** [comment]
# @Wufe i committed check pls

**Comment by Wufe** [comment]
I don't think it is closely related to react v16+: the demo page is based on react v16.4.2.
Can you recreate a minimal reproduce of the problem on codesandbox?
You can use [this one](https://codesandbox.io/s/40808yxrzx) as base.

**Comment by Wufe** [comment]
This should be solved with v2.5.0.
Feel free to reopen the issue if it has not been fixed and if you can submit a reproducible code.

**Comment by selimyalcin** [comment]
dude sorry for delay im working so hard. i can send u code tomorrow if bug still going
