### ISSUE TITLE
display particles on full display on Iphone SE view

### ISSUE THREAD

**Issue by wegosi** [Wufe/react-particles-js#88]
Hello, Please, check this issue on iphone SE view.

The bottom of the particles of div in not cover full screen. How to fix it?
![Screenshot_74](https://user-images.githubusercontent.com/17801144/59532084-6340d800-8ef0-11e9-91e7-63b2867eebb5.png)

Thank you

**Comment by Wufe** [comment]
The demo website is not designed for mobile.
However I'm not able to reproduce:

![image](https://user-images.githubusercontent.com/7671694/61589262-d8669380-aba7-11e9-8f01-ac7856af42d8.png)

Tried with Google Chrome on macOS and Windows 10.

If you think it may be useful to have a mobile layout for the demo page, feel free to open an issue or a pull request in the dedicated repository: [react-particles-js-demo](https://github.com/Wufe/react-particles-js-demo)
