### ISSUE TITLE
uncaught typeerror in console

### ISSUE THREAD

**Issue by 2016gx** [Wufe/react-particles-js#9]
Hi, I tried react-particles-js in my project, but there is an error in console:

"Uncaught TypeError: Super expression must either be null or a function, not undefined"

my react version is 0.14.2.

Please...

**Comment by Wufe** [comment]
Please tell me how to reproduce the problem, giving some hint or maybe some piece of code to work upon.

**Comment by Wufe** [comment]
No comments for 3 months. Closing the issue.
