### ISSUE TITLE
Polygon Mask not working with Gatsby

### ISSUE THREAD

**Issue by ambwani** [Wufe/react-particles-js#90]
Hi, there! I am getting the following error in my console.

```
particles.js:1 Uncaught (in promise) TypeError: Cannot read property 'numberOfItems' of undefined
    at particles.js:1
    at Array.forEach (<anonymous>)
    at particles.js:1
```

Any idea why I am getting this error? My SVG image is in my static folder, so it is accessible via root. I am unable to find a solution to this issue.

**Comment by Wufe** [comment]
You need to add the svgpathseg polyfill.
```html
<script src="https://cdn.rawgit.com/progers/pathseg/master/pathseg.js"></script>
```

**Comment by iagokrt** [comment]
I am wondering where should i add svgpathseg ?
``
<script src="https://cdn.rawgit.com/progers/pathseg/master/pathseg.js"></script>
``
into the static folder but where?

**Comment by SippingCode** [comment]
https://www.gatsbyjs.org/docs/custom-html/

This section can help. When copying your html.js add your <script> tag into the <head>
