### ISSUE TITLE
Bundle Size

### ISSUE THREAD

**Issue by diogotcorreia** [Wufe/react-particles-js#92]
The size of this repo is really big compared to the original project (particles.js).

According to BundlePhobia, the current min+gzipped size is [35kB](https://bundlephobia.com/result?p=react-particles-js@2.6.0) while the original particles.js is just [5.6kB](https://bundlephobia.com/result?p=particles.js@2.0.0).
Furthermore, versions 2.4.2 and older have a much more acceptable size at [11.1kB](https://bundlephobia.com/result?p=react-particles-js@2.4.2).

Why has the size suddenly increased in 2.5.0?

**Comment by Wufe** [comment]
Thanks for your report.

Bundle size has been restored to 15k gzipped ([Bundlephobia](https://bundlephobia.com/result?p=react-particles-js@2.7.0)).
I switched to es modules for lodash' `isEqual`.

New version is available: v2.7.0.

**Comment by GabrielmLinassi** [comment]
@Wufe bundle is 44.1kB Minified + Gzipped as of current version @3.4.1. Notice tsparticles is responsible for 86.8% of bundle size. Is there a way to decrease the size?
