### ISSUE TITLE
Linking to imported images

### ISSUE THREAD

**Issue by erebusstudio** [Wufe/react-particles-js#94]
Images work if you write their full url, but I cannot find how to use imported images for the polygon url.

Example :
```
import deer from './deer.svg';
...
"polygon": {
                  "url": {deer}
}
```

This doesn't work.
Is there a method to automatically add the link to the imported images to the "url" parameter ?

Thanks a lot in advance.

**Comment by Wufe** [comment]
If your bundler is creating an url from your import, just use

`"url": deer`

Check [this](https://github.com/Wufe/react-particles-js-demo/blob/master/src/frames.ts#L279) example (from the library demo repository).

**Comment by alexieyizhe** [comment]
@Wufe I can second the error where imported images do not show up when bundler is creating url from import.

**Comment by Wufe** [comment]
@alexieyizhe Please provide example code

**Comment by alexieyizhe** [comment]
Here's a rough example of a config with imported images:
```js
import { CircleParticle, SquareParticle } from "../images";

const particlesConfig = {
  particles: {
    number: {
      value: 25,
      density: {
        enable: true,
        value_area: 1000,
      },
    },
    line_linked: {
      enable: false,
    },
    move: {
      speed: 1,
      out_mode: "out",
    },
    shape: {
      type: ["images"],
      images: [
        {
          src: CircleParticle, // this will NOT show up
          height: 10,
          width: 10,
        },
        {
          src: SquareParticle, // this will NOT show up
          height: 10,
          width: 10,
        },
        {
          src: "/square.svg", // this WILL show up
          height: 10,
          width: 10,
        },
        {
          src: "/zigzag.svg", // this WILL show up
          height: 10,
          width: 10,
        },
      ],
    },
    color: {
      value: "#CCC",
    },
    size: {
      value: 10,
      random: true,
    },
  },
  retina_detect: false,
};
```

**Comment by Wufe** [comment]
@alexieyizhe Make sure the content of CircleParticle and SquareParticle is a **string**, containing a **reachable url**.

For example, if your environment is hosting the page at `http://localhost:8080` and the CircleParticle variable contains `../image.jpg`, the resulting url would be `http://localhost:8080/../image.jpg` ( which is not reachable).

If your bundler creates an image url like `/image.38cfa92[..].jpg`and it is reachable at `http://localhost:8080/image.38cfa92[..].jpg`, it will work.

**Comment by alexieyizhe** [comment]
@Wufe I believe that `CircleParticle` and `SquareParticle` are valid string image URLs. I've imported them in other components and used them in cases like `<img src={CircleParticle} />` with no issue.

**Comment by Wufe** [comment]
@alexieyizhe Can you provide a reproducible example within [CodeSandbox](https://codesandbox.io/) ?

**Comment by leetmachine** [comment]
Tested this out for single Image and it works. Appears to only have an issue with the multiple ['images'].

```
shape: {
      type: ["image"],
      image: {
        src: CircleParticle, // this works
        height: 10,
        width: 10,
      },
    },
```

**Comment by LNR14** [comment]
> 
> 
> If your bundler is creating an url from your import, just use
> 
> `"url": deer`
> 
> Check [this](https://github.com/Wufe/react-particles-js-demo/blob/master/src/frames.ts#L279) example (from the library demo repository).

This saved me a lot of time thanks a bunch
