### ISSUE TITLE
does the params shape follow the particle.js params shape

### ISSUE THREAD

**Issue by petervijeh** [Wufe/react-particles-js#98]
doesn't appear to respond at all to these inputs.  

                    "move": {
                      "enable": true,
                      "speed": 12,
                      "direction": "top",
                      "random": false,
                      "straight": false,
                    }
                    "particles": {
                      "number": {
                        "value": 80
                      },
                      "size": {
                        "value": 50,
                        "random": true,
                      }
                    },
                    "interactivity": {
                      "events": {
                        "onhover": {
                          "enable": true,
                          "mode": "repulse"
                        }
                      }
                    },

**Comment by petervijeh** [comment]
id recommend making the params API follow what particle.js uses,  this seems pretty useless :(

**Comment by Wufe** [comment]
They do follow the particles.js interface.
[Here](https://github.com/Wufe/react-particles-js/blob/master/index.d.ts) you can find the detailed shape of the `params` object and [here](https://vincentgarreau.com/particles.js/) you can create it interactively.
The snippet you sent is missing a comma after the `move` object and it should be placed under `particles` object.
